version: "3.9"

networks:
  internal:
    driver: bridge

services:
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres-new
    volumes:
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=new_db
      - POSTGRES_USER=innovatex
      - POSTGRES_PASSWORD=qwerty
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U onelab -d onelab_db" ]
      interval: 10s
      timeout: 5s
      retries: 5